import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, CalendarDays, CheckCircle2, ChevronRight, FileText, LayoutDashboard, MoreHorizontal, Plus, Search, Settings, Sparkles, Star, X } from 'lucide-react';
import './styles.css';

type Course = {id:number; title:string; code:string; professor:string; color:string; progress:number; lessons:number; completed:number; status:string; icon:string};
const initialCourses: Course[] = [
  {id:1,title:'Arquitectura de Software',code:'ARQ-401',professor:'Dra. Ana Torres',color:'#7257e8',progress:68,lessons:12,completed:8,status:'En progreso',icon:'◈'},
  {id:2,title:'Java Avanzado',code:'CS-312',professor:'Ing. Mateo Ruiz',color:'#23a47a',progress:42,lessons:16,completed:7,status:'En progreso',icon:'⌘'},
  {id:3,title:'Bases de Datos',code:'BD-210',professor:'Lucía Campos',color:'#e58a42',progress:88,lessons:10,completed:9,status:'En progreso',icon:'▦'},
];
const nav = [{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'courses',label:'Cursos',icon:BookOpen},{id:'notes',label:'Notas',icon:FileText},{id:'calendar',label:'Calendario',icon:CalendarDays}];

function Login({done}:{done:(name:string)=>void}){const setup=!localStorage.getItem('sh-account');const [error,setError]=useState('');const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),user=String(f.get('user')),pass=String(f.get('password'));if(setup){localStorage.setItem('sh-account',JSON.stringify({user,pass}));done(user)}else{const a=JSON.parse(localStorage.getItem('sh-account')||'{}');a.user===user&&a.pass===pass?done(user):setError('Credenciales incorrectas')}};return <div className="login"><form className="modal" onSubmit={submit}><div className="brand"><span className="brandmark">S</span>studyhub</div><h1>{setup?'Crea tu acceso':'Inicia sesión'}</h1><p className="muted">{setup?'Tu espacio será privado en este dispositivo.':'Bienvenido de nuevo.'}</p><label>Usuario<input required name="user" defaultValue={setup?'Harold':''}/></label><label>Contraseña<input required minLength={6} name="password" type="password"/></label>{error&&<p>{error}</p>}<button className="primary">{setup?'Crear acceso':'Entrar'}</button></form></div>}
function App(){
 const [session,setSession]=useState(()=>localStorage.getItem('sh-session')||''), [page,setPage]=useState('dashboard'), [courses,setCourses]=useState<Course[]>(()=>JSON.parse(localStorage.getItem('sh-courses')||'null')||initialCourses), [query,setQuery]=useState(''), [modal,setModal]=useState(false), [dark,setDark]=useState(false);
 useEffect(()=>localStorage.setItem('sh-courses',JSON.stringify(courses)),[courses]); if(!session)return <Login done={name=>{localStorage.setItem('sh-session',name);setSession(name)}}/>;
 const found=useMemo(()=>courses.filter(c=>c.title.toLowerCase().includes(query.toLowerCase())),[courses,query]);
 const addCourse=(form:FormData)=>{ const title=String(form.get('title')||'Nuevo curso'); setCourses([...courses,{id:Date.now(),title,code:String(form.get('code')||'SIN-CÓDIGO'),professor:String(form.get('professor')||'Por asignar'),color:'#e66c5a',progress:0,lessons:0,completed:0,status:'No iniciado',icon:'✦'}]); setModal(false);setPage('courses') };
 return <div className={dark?'app dark':'app'}>
  <aside><div className="brand"><span className="brandmark">S</span><span>studyhub</span></div><div className="workspace"><span className="avatar">H</span><div><b>Harold</b><small>Espacio personal</small></div><ChevronRight size={16}/></div>
  <nav>{nav.map(n=>{const Icon=n.icon;return <button className={page===n.id?'active':''} onClick={()=>setPage(n.id)} key={n.id}><Icon size={18}/>{n.label}</button>})}</nav>
  <div className="navlabel">ORGANIZAR</div><nav><button><Search size={18}/>Buscar <kbd>⌘ K</kbd></button><button><Star size={18}/>Favoritos</button><button onClick={()=>setPage('settings')} className={page==='settings'?'active':''}><Settings size={18}/>Configuración</button></nav>
  <div className="sidebottom"><button onClick={()=>setDark(!dark)}><span className="theme-dot"/> {dark?'Tema claro':'Tema oscuro'}</button><div className="tip"><Sparkles size={15}/><span><b>Tu racha va muy bien</b><br/>4 días aprendiendo</span></div></div></aside>
  <main><header><div className="mobilebrand">studyhub</div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en tu espacio..."/><kbd>⌘ K</kbd></div><button className="bell">◔</button><div className="avatar">H</div></header>
  {page==='dashboard' && <Dashboard courses={courses} setPage={setPage} onNew={()=>setModal(true)} />}
  {page==='courses' && <Courses courses={found} query={query} onNew={()=>setModal(true)} />}
  {page==='notes' && <Notes />}{page==='calendar' && <Calendar />}{page==='settings' && <SettingsPage />}
  </main>
  {modal&&<NewCourse onClose={()=>setModal(false)} onSave={addCourse}/>} </div>
}
function Dashboard({courses,setPage,onNew}:{courses:Course[],setPage:(p:string)=>void,onNew:()=>void}){const totals=courses.reduce((a,c)=>a+c.lessons,0); return <div className="page"><div className="hero"><div><p className="eyebrow">MIÉRCOLES, 29 DE JULIO</p><h1>Buenos días, Harold <span>✦</span></h1><p className="muted">Un pequeño avance hoy es progreso para mañana.</p></div><button className="primary" onClick={onNew}><Plus size={18}/>Nuevo curso</button></div><section className="metrics"><Metric icon="◈" value={courses.length} label="Cursos activos" tone="purple"/><Metric icon="✓" value={totals} label="Clases totales" tone="green"/><Metric icon="▤" value="24" label="Notas guardadas" tone="orange"/><Metric icon="◷" value="18.5 h" label="Esta semana" tone="blue"/></section><section className="grid"><div className="panel wide"><div className="panelhead"><div><h2>Continúa aprendiendo</h2><p>Retoma donde lo dejaste</p></div><button className="link" onClick={()=>setPage('courses')}>Ver todos <ChevronRight size={16}/></button></div><div className="course-list">{courses.map(c=><article className="course-row" key={c.id}><div className="course-icon" style={{background:c.color}}>{c.icon}</div><div className="grow"><div className="rowtitle"><div><h3>{c.title}</h3><p>{c.code} · {c.professor}</p></div><button className="iconbtn"><MoreHorizontal size={19}/></button></div><div className="progressline"><span style={{width:c.progress+'%',background:c.color}}/></div><div className="progressmeta"><span>{c.completed} de {c.lessons} clases completadas</span><b>{c.progress}%</b></div></div></article>)}</div></div><div className="panel agenda"><div className="panelhead"><div><h2>Próximamente</h2><p>Tu agenda de estudio</p></div><button className="iconbtn"><CalendarDays size={18}/></button></div><div className="event"><span className="date">30<br/><small>JUL</small></span><div><b>Clase 09 · Patrones</b><p>Arquitectura de Software · 10:00</p></div></div><div className="event"><span className="date orange">01<br/><small>AGO</small></span><div><b>Entrega · Proyecto API</b><p>Java Avanzado · 23:59</p></div></div><button className="fullbutton">Ver calendario</button></div></section><section className="panel activity"><div className="panelhead"><div><h2>Actividad reciente</h2></div><button className="link">Ver historial <ChevronRight size={16}/></button></div><div className="activity-row"><span className="round green"><CheckCircle2 size={17}/></span><div><b>Completaste “Patrón Strategy”</b><p>Arquitectura de Software · Hace 2 horas</p></div></div><div className="activity-row"><span className="round purple"><FileText size={16}/></span><div><b>Editaste tus apuntes de Streams</b><p>Java Avanzado · Ayer</p></div></div></section></div>}
function Metric({icon,value,label,tone}:{icon:string,value:string|number,label:string,tone:string}){return <div className="metric"><span className={'metricicon '+tone}>{icon}</span><div><b>{value}</b><p>{label}</p></div></div>}
function Courses({courses,query,onNew}:{courses:Course[],query:string,onNew:()=>void}){return <div className="page"><div className="hero"><div><p className="eyebrow">BIBLIOTECA PERSONAL</p><h1>Mis cursos</h1><p className="muted">Organiza cada objetivo de aprendizaje en un solo lugar.</p></div><button className="primary" onClick={onNew}><Plus size={18}/>Nuevo curso</button></div><div className="filterbar"><button className="filter active">Todos <b>{courses.length}</b></button><button className="filter">En progreso</button><button className="filter">Finalizados</button></div><div className="coursegrid">{courses.map(c=><article className="coursecard" key={c.id}><div className="cardtop" style={{background:`linear-gradient(130deg, ${c.color}, ${c.color}aa)`}}><span>{c.icon}</span><button><MoreHorizontal size={18}/></button></div><div className="cardbody"><div className="status"><i style={{background:c.color}}/>{c.status}</div><h2>{c.title}</h2><p>{c.code} · {c.professor}</p><div className="cardprogress"><div><span style={{width:c.progress+'%',background:c.color}}/></div><b>{c.progress}%</b></div><p className="lessoncount"><CheckCircle2 size={15}/>{c.completed}/{c.lessons} clases completadas</p></div></article>)}{!courses.length&&<div className="empty">No encontramos cursos para “{query}”.</div>}</div></div>}
function Notes(){return <div className="page"><div className="hero"><div><p className="eyebrow">CONOCIMIENTO</p><h1>Notas</h1><p className="muted">Ideas, resúmenes y referencias en un espacio sin distracciones.</p></div><button className="primary"><Plus size={18}/>Nueva nota</button></div><div className="notes"><article><span>⌘</span><small>JAVA · HOY</small><h2>Streams y programación funcional</h2><p>Operaciones intermedias, terminales y ejemplos con colecciones…</p><div>#Java #Backend</div></article><article><span>◈</span><small>ARQUITECTURA · AYER</small><h2>Principios SOLID</h2><p>Una guía práctica para tomar decisiones de diseño sostenibles.</p><div>#Arquitectura #Diseño</div></article></div></div>}
function Calendar(){return <div className="page"><div className="hero"><div><p className="eyebrow">PLANIFICACIÓN</p><h1>Calendario</h1><p className="muted">Clases, entregas y recordatorios de julio.</p></div><button className="primary"><Plus size={18}/>Agregar evento</button></div><div className="calendar"><div className="calhead"><b>Julio 2026</b><span>‹ &nbsp; Hoy &nbsp; ›</span></div><div className="week">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=><b key={x}>{x}</b>)}</div><div className="days">{Array.from({length:31},(_,i)=><div className={i===28?'today':''} key={i}><b>{i+1}</b>{i===29&&<span className="cal-event purple">Clase · Patrones</span>}{i===30&&<span className="cal-event orange">Entrega API</span>}</div>)}</div></div></div>}
function SettingsPage(){return <div className="page"><div className="hero"><div><p className="eyebrow">PREFERENCIAS</p><h1>Configuración</h1><p className="muted">Personaliza tu espacio de aprendizaje.</p></div></div><div className="settings"><section><h2>Perfil</h2><div className="profile"><span className="avatar big">H</span><div><b>Harold</b><p>harold@studyhub.local</p></div><button className="outline">Cambiar foto</button></div></section><section><h2>Cuenta</h2><button className="settingrow">Cambiar contraseña <ChevronRight size={18}/></button><button className="settingrow">Exportar mi información <ChevronRight size={18}/></button></section></div></div>}
function NewCourse({onClose,onSave}:{onClose:()=>void,onSave:(f:FormData)=>void}){return <div className="overlay"><form className="modal" onSubmit={event=>{event.preventDefault();onSave(new FormData(event.currentTarget));}}><div className="modalhead"><div><h2>Crear curso</h2><p>Empieza a organizar un nuevo objetivo.</p></div><button type="button" onClick={onClose}><X size={20}/></button></div><label>Nombre del curso<input required name="title" placeholder="Ej. Diseño de sistemas" autoFocus/></label><div className="twocol"><label>Código<input name="code" placeholder="CS-400"/></label><label>Profesor<input name="professor" placeholder="Nombre del profesor"/></label></div><div className="modalactions"><button type="button" className="outline" onClick={onClose}>Cancelar</button><button className="primary">Crear curso</button></div></form></div>}
createRoot(document.getElementById('root')!).render(<App/>);
